// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Web Dec 25 12:22:21 2019
`timescale 1ns/1ps

module demux_tb;

reg [4:0] i_ADDR_sig;
reg i_data_sig;
wire [31:0] o_data_sig;

demux_ver demux_ver_inst
(
	.i_ADDR(i_ADDR_sig) ,	// input [4:0] i_ADDR_sig
	.i_data(i_data_sig) ,	// input  i_data_sig
	.o_data(o_data_sig) 	// output [31:0] o_data_sig
);

initial begin
	i_data_sig = 1'b1;
end

initial begin
	i_ADDR_sig = 4'b0000;
	
	forever #1 i_ADDR_sig = i_ADDR_sig + 1;
end

initial begin
	#100 $stop();
end

endmodule

